Ark pentahoee pr
ArkCase/ark_pentaho_ee pull request #1
Opened 2021-08-16 18:02 UTC by dheeraj-armedia

"Pentaho-EE PR"

2021-08-16 19:03 UTC, fabricetriboix requested changes

2021-08-16 19:03 UTC, fabricetriboix commented on Dockerfile
> +COPY expect-script-pdi.exp /home/pentaho/app/pentaho-pdi
All those expect scripts are absent from the repo. Did you forget to add them to git?

2021-08-17 04:30 UTC, dheeraj-armedia commented on Dockerfile
> +#-----------Expect script to exract all packages-------------------------------
Its not typo its expect script , Which will unpack all penatho ee packages . Also we need install expect to run this script (yum install expect)

2021-08-17 04:47 UTC, dheeraj-armedia commented on Dockerfile
> +    sh ${PENTAHO_PDI_LICENSE}/install_license.sh  install -q "${PENTAHO_LICENSE_PATH}/Pentaho PDI Enterprise Edition.lic"
Sure i will remove license files , Once license install is completed

2021-08-17 05:28 UTC, dheeraj-armedia commented on Dockerfile
> +COPY ${RESOURCE_PATH}/pentaho-server-licenses-${PENTAHO_SERVER_LICENSES}.zip ${RESOURCE_PATH}/pir-plugin-ee-${PIR_PLUGIN_EE}-dist.zip ${RESOURCE_PATH}/paz-plugin-ee-${PAZ_PLUGIN_EE}-dist.zip ${RESOUR
Sure i will do that

2021-08-17 05:46 UTC, dheeraj-armedia commented on Dockerfile
> +      MAINTAINER="Armedia LLC"
Changed MAINTAINER to Armedia Devops Team <devops@armedia.com>

2021-08-17 07:15 UTC, dheeraj-armedia commented on Dockerfile
> +COPY expect-script-pdi.exp /home/pentaho/app/pentaho-pdi
This file will be in s3 bucket.

2021-08-17 08:00 UTC, dheeraj-armedia commented on Dockerfile
> +ENV PENTAHO_SERVER_EE=8.3.0.0-371 \
@fabricetriboix Made changes and committed code

2021-08-17 09:00 UTC, fabricetriboix commented on Dockerfile
> +#-----------Expect script to exract all packages-------------------------------
I am not talking about "expect". You wrote "exract" in the comment, it should be "extract".

2021-08-17 09:05 UTC, fabricetriboix commented on Dockerfile
> +COPY expect-script-pdi.exp /home/pentaho/app/pentaho-pdi
OK, I can see the `get-artifacts.sh` script is pulling them now. There is still a problem because the `get-artifacts.sh` script put them into the `artifacts` folder and the Dockerfile wants to copy them from the root of the project, so there is a mismatch there.

However, generally speaking, I would expect (no pun intended) these scripts to be located in the git repo itself and thus brought under version control. Is there any good reason why we shouldn't do this? I think such small files (and especially text files), should live in the git repo.

2021-08-17 09:09 UTC, dheeraj-armedia commented on Dockerfile
> +#-----------Expect script to exract all packages-------------------------------
Got it @fabricetriboix i will correct that

2021-08-17 09:09 UTC, fabricetriboix requested changes

2021-08-17 09:09 UTC, fabricetriboix commented on get-artifacts.sh
> +aws s3 cp "s3://arkcase-container-artifacts/ark_pentaho_ee/expect-script-pir.exp" artifacts/
Please consider moving those scripts into the git repo

2021-08-17 09:44 UTC, dheeraj-armedia commented on Dockerfile
> +COPY expect-script-pdi.exp /home/pentaho/app/pentaho-pdi
@fabricetriboix Moved file to git repo and according to this changes made in Docker and get-artifacts.sh file

2021-08-17 10:07 UTC, fabricetriboix approved these changes

2021-08-17 17:06 UTC, JonHolman commented on Dockerfile
> +      VERSION="1.0" \
please add an APP label.

2021-08-17 17:06 UTC, JonHolman commented on Dockerfile
> +    mkdir -p /home/pentaho/install     &&  \
minor, but since the next mkdir is under /install this line does not need to be here.

2021-08-17 17:06 UTC, JonHolman commented on get-artifacts.sh
> +aws s3 cp "s3://arkcase-container-artifacts/ark_pentaho_ee/arkcase-preauth-springsec-v${ARKCASE_PRE_AUTH_VERSION}-bundled.jar" artifacts/
this could be one command to copy the contents of ark_pentaho_ee to artifacts?  using --recursive?

2021-08-18 05:38 UTC, dheeraj-armedia commented on Dockerfile
> +    PENTAHO_PDI_LICENSE=/home/pentaho/app/pentaho-pdi/license-installer \
@JonHolman Already tried with /app path but facing few issues , so i am keep same path /home/penatho/app/pentaho

2021-08-18 05:40 UTC, dheeraj-armedia commented on Dockerfile
> +      VERSION="1.0" \
Sure jon i will add and i will commit code

2021-08-18 06:16 UTC, dheeraj-armedia commented on get-artifacts.sh
> +aws s3 cp "s3://arkcase-container-artifacts/ark_pentaho_ee/arkcase-preauth-springsec-v${ARKCASE_PRE_AUTH_VERSION}-bundled.jar" artifacts/
@JonHolman changed and committed code. (aws s3 cp --recursive  s3://arkcase-container-artifacts/ark_pentaho_ee/  artifacts/)

2021-08-19 07:33 UTC, fabricetriboix approved these changes
Please make the `get-artifacts.sh` script executable

2021-08-19 13:02 UTC, JonHolman approved these changes

2021-08-19 13:45 UTC, fabricetriboix approved these changes

2021-08-20 06:05 UTC, merged